version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: odoo-db
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: odoo
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - odoo-network
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo"]
      interval: 30s
      timeout: 10s
      retries: 5

  odoo:
    build: .
    container_name: odoo-container
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8069:8069"
      - "8071:8071"
      - "8072:8072"
    volumes:
      - odoo-data:/var/lib/odoo
      - ./extra-addons:/mnt/extra-addons
    environment:
      HOST: db
      PORT: 5432
      USER: odoo
      PASSWORD: odoo
    networks:
      - odoo-network

volumes:
  db-data:
  odoo-data:

networks:
  odoo-network: